Category.create(name: 'Command Over Resources')
Category.create(name: 'Innovation and Technology')
Category.create(name: 'Environment')
Category.create(name: 'International Capital Flows and Migrations')
Category.create(name: 'International Trade Flows of Goods and Services')
Category.create(name: 'Education')
Category.create(name: 'Health')
Category.create(name: 'Population')
Category.create(name: 'Gender Inequality Index')
Category.create(name: 'Multidimensional Poverty Index')